name: youtube_caption_scraper
description: Parse subtitles/captions from YouTube without authorization.
version: 0.2.0
homepage: https://github.com/f-person/youtube_captions_scraper
repository: https://github.com/f-person/youtube_captions_scraper

environment:
  sdk: ">=2.16.0 <4.0.0"

dependencies:
  html: ^0.15.4
  http: ^0.13.0

dev_dependencies:
  lints: ^2.1.1
  test: ^1.24.6

false_secrets:
  - test/test_data.dart
